import './globals.css'
import '../../styles/slim/slim.scss';
import Head from "next/head";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      {/*<Head />*/}
      <head>
          <title>PsychoDevs</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={'anonymous'}/>
            <link
                href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Noto+Sans:ital@0;1&family=Poppins:wght@700&display=swap"
                rel="stylesheet"/>
      </head>
      <body className={'apple dark blue'}>{children}</body>
    </html>
  )
}
